kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-distribusjon
  namespace: amt
  labels:
    team: amt
spec:
  image: {{image}}
  port: 8080
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  startup:
    path: /internal/health/liveness
    initialDelay: 30
    failureThreshold: 45
    periodSeconds: 5
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 2048Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
  secureLogs:
    enabled: true
  leaderElection: true
  kafka:
    pool: nav-dev
  accessPolicy:
    outbound:
      rules:
        - application: amt-pdfgen
        - application: amt-person-service
      external:
        - host: amt-unleash-api.nav.cloud.nais.io
        - host: veilarboppfolging.dev-fss-pub.nais.io
        - host: dokarkiv-q2.dev-fss-pub.nais.io
  envFrom:
    - secret: amt-distribusjon-unleash-api-token
  gcp:
    sqlInstances:
      - name: amt-distribusjon
        collation: nb_NO.UTF8
        type: POSTGRES_14
        databases:
          - name: amt-distribusjon
            envVarPrefix: DB
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  env:
    - name: AMT_PERSONSERVICE_SCOPE
      value: api://dev-gcp.amt.amt-person-service/.default
    - name: AMT_PERSONSERVICE_URL
      value: http://amt-person-service
    - name: AMT_PDFGEN_SCOPE
      value: api://dev-gcp.amt.amt-pdfgen/.default
    - name: AMT_PDFGEN
      value: http://amt-pdfgen
    - name: VEILARBOPPFOLGING_SCOPE
      value: api://dev-fss.pto.veilarboppfolging/.default
    - name: VEILARBOPPFOLGING_URL
      value: https://veilarboppfolging.dev-fss-pub.nais.io
    - name: DOKARKIV_URL
      value: https://dokarkiv-q2.dev-fss-pub.nais.io
    - name: DOKARKIV_SCOPE
      value: api://dev-fss.teamdokumenthandtering.dokarkiv/.default
    - name: DOKDISTKANAL_URL
      value: https://dokdistkanal-q2.dev-fss-pub.nais.io
    - name: DOKDISTKANAL_SCOPE
      value: api://dev-fss.teamdokumenthandtering.dokdistkanal/.default
    - name: DOKDISTFORDELING_URL
      value: https://dokdistfordeling.dev-fss-pub.nais.io
    - name: SAF_SCOPE
      value: api://dev-fss.teamdokumenthandtering.saf/.default
