elector.path=dont_look_for_leader

### App
app.app-name=${NAIS_APP_NAME:amt-distribusjon}
app.amt-deltaker-url=http://localhost/amt-deltaker-api
app.dok-dist-kanal-url=http://localhost/dok-dist-kanal-api
app.dok-arkiv-url=http://localhost/dok-arkiv-api
app.dok-dist-fordeling-url=http://localhost/dok-dist-fordeling-api
app.pdf-gen-url=http://localhost/pdf-gen-api
app.person-service-url=http://localhost/amt-person-api
app.veilarbo-url=http://localhost/veilarboppfolging-api


### JWT Issuers
no.nav.security.jwt.issuer.tokenx.discovery-url=http://localhost:${mock-oauth2-server.port}/tokenx/.well-known/openid-configuration
no.nav.security.jwt.issuer.tokenx.accepted-audience=amt-distribusjon-client-id

no.nav.security.jwt.issuer.azureator.discovery-url=http://localhost:${mock-oauth2-server.port}/azuread/.well-known/openid-configuration
no.nav.security.jwt.issuer.azureator.accepted-audience=amt-distribusjon-client-id

### JWT Clients ? amt-deltaker-aad
no.nav.security.jwt.client.registration.amt-deltaker-aad.token-endpoint-url=http://localhost:${mock-oauth2-server.port}/azureator/token
no.nav.security.jwt.client.registration.amt-deltaker-aad.grant-type=client_credentials
no.nav.security.jwt.client.registration.amt-deltaker-aad.scope=amt-deltaker
no.nav.security.jwt.client.registration.amt-deltaker-aad.authentication.client-id=clientid
no.nav.security.jwt.client.registration.amt-deltaker-aad.authentication.client-secret=secret
no.nav.security.jwt.client.registration.amt-deltaker-aad.authentication.client-auth-method=client_secret_basic


### JWT Clients ? dok-dist-kanal-aad
no.nav.security.jwt.client.registration.dok-dist-kanal-aad.token-endpoint-url=http://localhost:${mock-oauth2-server.port}/azureator/token
no.nav.security.jwt.client.registration.dok-dist-kanal-aad.grant-type=client_credentials
no.nav.security.jwt.client.registration.dok-dist-kanal-aad.scope=dev-fss-pub
no.nav.security.jwt.client.registration.dok-dist-kanal-aad.authentication.client-id=clientid
no.nav.security.jwt.client.registration.dok-dist-kanal-aad.authentication.client-secret=secret
no.nav.security.jwt.client.registration.dok-dist-kanal-aad.authentication.client-auth-method=client_secret_basic


### JWT Clients ? dok-arkiv-aad
no.nav.security.jwt.client.registration.dok-arkiv-aad.token-endpoint-url=http://localhost:${mock-oauth2-server.port}/azureator/token
no.nav.security.jwt.client.registration.dok-arkiv-aad.grant-type=client_credentials
no.nav.security.jwt.client.registration.dok-arkiv-aad.scope=dokarkiv
no.nav.security.jwt.client.registration.dok-arkiv-aad.authentication.client-id=clientid
no.nav.security.jwt.client.registration.dok-arkiv-aad.authentication.client-secret=secret
no.nav.security.jwt.client.registration.dok-arkiv-aad.authentication.client-auth-method=client_secret_basic


### JWT Clients ? dok-dist-fordeling-aad
no.nav.security.jwt.client.registration.dok-dist-fordeling-aad.token-endpoint-url=http://localhost:${mock-oauth2-server.port}/azureator/token
no.nav.security.jwt.client.registration.dok-dist-fordeling-aad.grant-type=client_credentials
no.nav.security.jwt.client.registration.dok-dist-fordeling-aad.scope=dokdistfordeling
no.nav.security.jwt.client.registration.dok-dist-fordeling-aad.authentication.client-id=clientid
no.nav.security.jwt.client.registration.dok-dist-fordeling-aad.authentication.client-secret=secret
no.nav.security.jwt.client.registration.dok-dist-fordeling-aad.authentication.client-auth-method=client_secret_basic


### JWT Clients ? pdf-gen-aad
no.nav.security.jwt.client.registration.pdf-gen-aad.token-endpoint-url=http://localhost:${mock-oauth2-server.port}/azureator/token
no.nav.security.jwt.client.registration.pdf-gen-aad.grant-type=client_credentials
no.nav.security.jwt.client.registration.pdf-gen-aad.scope=amt-pdfgen
no.nav.security.jwt.client.registration.pdf-gen-aad.authentication.client-id=clientid
no.nav.security.jwt.client.registration.pdf-gen-aad.authentication.client-secret=secret
no.nav.security.jwt.client.registration.pdf-gen-aad.authentication.client-auth-method=client_secret_basic


### JWT Clients ? amt-person-aad
no.nav.security.jwt.client.registration.amt-person-aad.token-endpoint-url=http://localhost:${mock-oauth2-server.port}/azureator/token
no.nav.security.jwt.client.registration.amt-person-aad.grant-type=client_credentials
no.nav.security.jwt.client.registration.amt-person-aad.scope=amt-person-service
no.nav.security.jwt.client.registration.amt-person-aad.authentication.client-id=clientid
no.nav.security.jwt.client.registration.amt-person-aad.authentication.client-secret=secret
no.nav.security.jwt.client.registration.amt-person-aad.authentication.client-auth-method=client_secret_basic


### JWT Clients ? veilarboppfolging-aad
no.nav.security.jwt.client.registration.veilarboppfolging-aad.token-endpoint-url=http://localhost:${mock-oauth2-server.port}/azureator/token
no.nav.security.jwt.client.registration.veilarboppfolging-aad.grant-type=client_credentials
no.nav.security.jwt.client.registration.veilarboppfolging-aad.scope=veilarboppfolging
no.nav.security.jwt.client.registration.veilarboppfolging-aad.authentication.client-id=clientid
no.nav.security.jwt.client.registration.veilarboppfolging-aad.authentication.client-secret=secret
no.nav.security.jwt.client.registration.veilarboppfolging-aad.authentication.client-auth-method=client_secret_basic
