### Spring
spring.main.banner-mode=off
spring.threads.virtual.enabled=true
  
  ### Server
server.shutdown=graceful
  
  
  ### Management / Actuator
management.endpoint.prometheus.access=read_only
management.endpoint.health.probes.enabled=true
management.endpoint.health.group.liveness.include=livenessState

management.endpoints.web.base-path=/internal
management.endpoints.web.exposure.include=prometheus,health

management.prometheus.metrics.export.enabled=true
  
  
  ### App
app.app-name=${NAIS_APP_NAME:amt-distribusjon}
app.amt-deltaker-url=${AMT_DELTAKER_URL}
app.dok-dist-kanal-url=${DOKDISTKANAL_URL}
app.dok-arkiv-url=${DOKARKIV_URL}
app.dok-dist-fordeling-url=${DOKDISTFORDELING_URL}
app.pdf-gen-url=${AMT_PDFGEN}
app.person-service-url=${AMT_PERSONSERVICE_URL}
app.veilarbo-url=${VEILARBOPPFOLGING_URL}
  
  
  ### JWT Issuers
no.nav.security.jwt.issuer.tokenx.discovery-url=${TOKEN_X_WELL_KNOWN_URL}
no.nav.security.jwt.issuer.tokenx.accepted-audience=${TOKEN_X_CLIENT_ID}

no.nav.security.jwt.issuer.azureator.discovery-url=${AZURE_APP_WELL_KNOWN_URL}
no.nav.security.jwt.issuer.azureator.accepted-audience=${AZURE_APP_CLIENT_ID}
  
  
  ### JWT Clients – amt-deltaker-aad
no.nav.security.jwt.client.registration.amt-deltaker-aad.token-endpoint-url=${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
no.nav.security.jwt.client.registration.amt-deltaker-aad.grant-type=client_credentials
no.nav.security.jwt.client.registration.amt-deltaker-aad.scope=${AMT_DELTAKER_SCOPE}
no.nav.security.jwt.client.registration.amt-deltaker-aad.authentication.client-id=${AZURE_APP_CLIENT_ID}
no.nav.security.jwt.client.registration.amt-deltaker-aad.authentication.client-secret=${AZURE_APP_CLIENT_SECRET}
no.nav.security.jwt.client.registration.amt-deltaker-aad.authentication.client-auth-method=client_secret_basic
  
  
  ### JWT Clients – dok-dist-kanal-aad
no.nav.security.jwt.client.registration.dok-dist-kanal-aad.token-endpoint-url=${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
no.nav.security.jwt.client.registration.dok-dist-kanal-aad.grant-type=client_credentials
no.nav.security.jwt.client.registration.dok-dist-kanal-aad.scope=${DOKDISTKANAL_SCOPE}
no.nav.security.jwt.client.registration.dok-dist-kanal-aad.authentication.client-id=${AZURE_APP_CLIENT_ID}
no.nav.security.jwt.client.registration.dok-dist-kanal-aad.authentication.client-secret=${AZURE_APP_CLIENT_SECRET}
no.nav.security.jwt.client.registration.dok-dist-kanal-aad.authentication.client-auth-method=client_secret_basic
  
  
  ### JWT Clients – dok-arkiv-aad
no.nav.security.jwt.client.registration.dok-arkiv-aad.token-endpoint-url=${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
no.nav.security.jwt.client.registration.dok-arkiv-aad.grant-type=client_credentials
no.nav.security.jwt.client.registration.dok-arkiv-aad.scope=${DOKARKIV_SCOPE}
no.nav.security.jwt.client.registration.dok-arkiv-aad.authentication.client-id=${AZURE_APP_CLIENT_ID}
no.nav.security.jwt.client.registration.dok-arkiv-aad.authentication.client-secret=${AZURE_APP_CLIENT_SECRET}
no.nav.security.jwt.client.registration.dok-arkiv-aad.authentication.client-auth-method=client_secret_basic
  
  
  ### JWT Clients – dok-dist-fordeling-aad
no.nav.security.jwt.client.registration.dok-dist-fordeling-aad.token-endpoint-url=${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
no.nav.security.jwt.client.registration.dok-dist-fordeling-aad.grant-type=client_credentials
no.nav.security.jwt.client.registration.dok-dist-fordeling-aad.scope=${DOKDISTFORDELING_SCOPE}
no.nav.security.jwt.client.registration.dok-dist-fordeling-aad.authentication.client-id=${AZURE_APP_CLIENT_ID}
no.nav.security.jwt.client.registration.dok-dist-fordeling-aad.authentication.client-secret=${AZURE_APP_CLIENT_SECRET}
no.nav.security.jwt.client.registration.dok-dist-fordeling-aad.authentication.client-auth-method=client_secret_basic
  
  
  ### JWT Clients – pdf-gen-aad
no.nav.security.jwt.client.registration.pdf-gen-aad.token-endpoint-url=${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
no.nav.security.jwt.client.registration.pdf-gen-aad.grant-type=client_credentials
no.nav.security.jwt.client.registration.pdf-gen-aad.scope=${AMT_PDFGEN_SCOPE}
no.nav.security.jwt.client.registration.pdf-gen-aad.authentication.client-id=${AZURE_APP_CLIENT_ID}
no.nav.security.jwt.client.registration.pdf-gen-aad.authentication.client-secret=${AZURE_APP_CLIENT_SECRET}
no.nav.security.jwt.client.registration.pdf-gen-aad.authentication.client-auth-method=client_secret_basic
  
  
  ### JWT Clients – amt-person-aad
no.nav.security.jwt.client.registration.amt-person-aad.token-endpoint-url=${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
no.nav.security.jwt.client.registration.amt-person-aad.grant-type=client_credentials
no.nav.security.jwt.client.registration.amt-person-aad.scope=${AMT_PERSONSERVICE_SCOPE}
no.nav.security.jwt.client.registration.amt-person-aad.authentication.client-id=${AZURE_APP_CLIENT_ID}
no.nav.security.jwt.client.registration.amt-person-aad.authentication.client-secret=${AZURE_APP_CLIENT_SECRET}
no.nav.security.jwt.client.registration.amt-person-aad.authentication.client-auth-method=client_secret_basic
  
  
  ### JWT Clients – veilarboppfolging-aad
no.nav.security.jwt.client.registration.veilarboppfolging-aad.token-endpoint-url=${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
no.nav.security.jwt.client.registration.veilarboppfolging-aad.grant-type=client_credentials
no.nav.security.jwt.client.registration.veilarboppfolging-aad.scope=${VEILARBOPPFOLGING_SCOPE}
no.nav.security.jwt.client.registration.veilarboppfolging-aad.authentication.client-id=${AZURE_APP_CLIENT_ID}
no.nav.security.jwt.client.registration.veilarboppfolging-aad.authentication.client-secret=${AZURE_APP_CLIENT_SECRET}
no.nav.security.jwt.client.registration.veilarboppfolging-aad.authentication.client-auth-method=client_secret_basic
