name: Deploy unleash-apitoken
on:
  push:
    paths:
      - ".nais/unleash-apitoken-dev.yaml"

jobs:
  deploy-dev:
    permissions:
      id-token: "write"
    name: Deploy unleash-apitoken to dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy application
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/unleash-apitoken-dev.yaml
